# Generated by Django 4.2.3 on 2023-10-15 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mealfooditem',
            name='total_kcal',
        ),
    ]
