# Generated by Django 4.2.3 on 2023-09-21 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_fooditem_name_alter_fooditem_unit_meal'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='qty',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
