# Generated by Django 4.2.3 on 2023-10-15 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_mealfooditem_total_kcal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fooditem',
            name='default_qty',
        ),
    ]
