# Generated by Django 4.2.3 on 2023-09-21 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_fooditem_qty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='qty',
            field=models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=6),
        ),
    ]
